language: "en"

pipeline: "pretrained_embeddings_spacy pipeline"

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy # Please comment out when your assistent not following the path defined in stories.md
  - name: MappingPolicy
